modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cmdlog"
version="1.0.0"
displayName="Command Log"
description='''플레이어의 명령어 사용을 날짜별 파일로 기록합니다.'''

[[dependencies.cmdlog]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.cmdlog]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
